name: 2 Adet Güvenli SSH Makinesi (Debug için)

on:
  workflow_dispatch:

jobs:
  setup-machines:
    name: 2 SSH Makinesi Kurulumu (Sadece Debug)
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
      - name: tmate Kurulumu
        run: |
          sudo apt-get update
          sudo apt-get install -y tmate

      - name: 2 tmate Oturumu Oluştur
        run: |
          echo "!!! DİKKAT: Bu SSH oturumları sadece debugging ve eğitim amaçlıdır. Saldırı, izinsiz erişim veya kötüye kullanım kesinlikle yasaktır. !!!"
          echo "" > ssh_info.txt
          for i in 1 2; do
            tmate -S /tmp/tmate$i.sock new-session -d
            tmate -S /tmp/tmate$i.sock wait tmate-ready
            MACHINE_NAME="Makine-$i"
            SSH_CMD=$(tmate -S /tmp/tmate$i.sock display -p '#{tmate_ssh}')
            echo "$MACHINE_NAME: $SSH_CMD" >> ssh_info.txt
          done

      - name: SSH Bilgilerini Artifact Olarak Yükle
        uses: actions/upload-artifact@v3
        with:
          name: ssh-info
          path: ssh_info.txt

      - name: Oturumları Açık Tut
        run: |
          echo "2 SSH oturumu 10 saat boyunca debugging için açık kalacak."
          echo "SSH bağlantı bilgilerini asla başkalarıyla paylaşmayın!"
          sleep 36000
